# Generated by Django 3.0.5 on 2023-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
